# Generated by Django 4.1.4 on 2023-01-12 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='create_at',
        ),
        migrations.RemoveField(
            model_name='emailverification',
            name='create_at',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='create_at',
        ),
        migrations.RemoveField(
            model_name='payplan',
            name='create_at',
        ),
    ]
