# Generated by Django 4.1.4 on 2023-01-12 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_remove_categories_create_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortenedurls',
            name='expired_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddIndex(
            model_name='shortenedurls',
            index=models.Index(fields=['prefix', 'shortened_url'], name='shortener_s_prefix_bbcd1e_idx'),
        ),
    ]
