# Generated by Django 4.1.4 on 2023-01-03 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shortener", "0002_userdetail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="pay_plan",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="shortener.payplan",
            ),
        ),
    ]
