# Generated by Django 4.1.4 on 2023-01-04 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shortener", "0003_alter_users_pay_plan"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserDetail",
        ),
    ]
