# Generated by Django 4.1.4 on 2023-01-19 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0006_users_telegram_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='industry',
            field=models.CharField(choices=[('personal', 'Personal'), ('retail', 'Retail'), ('manufacturing', 'Manufacturing'), ('it', 'It'), ('others', 'Others')], default='others', max_length=15),
        ),
    ]
